name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust Check & Test (OSS Mode)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Protoc (Required for Tonic Build)
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cargo Check
      run: cargo check --no-default-features

    - name: Cargo Test
      run: cargo test --no-default-features

    - name: Cargo Clippy
      run: cargo clippy --no-default-features -- -D warnings
